### PR TITLE
generate the required type for user business assets

### PR DESCRIPTION
**Pull request by EslaM-M**

### CODE REVIEW

**Review by OgulcanCelik — COMMENTED** [review]
thank you for the light speed PR, there are some unrelated comment deletions would be great if you could re-add them 👍 also you need to update the package version in `package.json` 😄

**Comment by EslaM-M** [comment]
> thank you for the light speed PR, there are some unrelated comment deletions would be great if you could re-add them 👍 also you need to update the package version in `package.json` 😄

@OgulcanCelik done 🙏

**Review by OgulcanCelik — APPROVED** [review]
🚀

**Review by sinahashemy — APPROVED** [review]
👍, would be better to bump the version in a separated pr as a release pr, it will prevent conflicts on the multiple pr simultaneously.

**Pull request merged**
