### PR TITLE
Re-generate schema for split's categorizationType

### PR DESCRIPTION
**Pull request by kolyose**
Requests for split's `categorizationType` attribute and updates the schemas accordingly

### CODE REVIEW

**Comment by p-janik** [comment]
@kolyose do you know why we such diff for `lib/graphql/schema.flow.js`?

**Comment by amodesKontist** [comment]
I think Sylvain once told me it is like this because when you use npm instead of yarn or have different yarn/npm versions 🤔

**Comment by kolyose** [comment]
@p-janik I can see the majority of the changes are whitespaces 🤔

**Comment by kolyose** [comment]
so I tried updating `yarn` to the latest version(s) (`1.22.10` & `2.4.0`), also I tried it with `npm` - all of them generate me the same schema with all the whitespaces removed at the eol 🤷‍♂️

**Comment by amodesKontist** [comment]
> so I tried updating `yarn` to the latest version(s) (`1.22.10` & `2.4.0`), also I tried it with `npm` - all of them generate me the same schema with all the trailing whitespaces removed 🤷‍♂️

Ok I checked with yarn v.1.22.10 and npm, and I get the trailing whitespaces :man-shrugging: 
Maybe we can create housekeeping ticket to investigate more

**Review by amodesKontist — APPROVED** [review]

**Pull request merged**
